output_dir: artifacts/model_trainer
overwrite_output_dir: false
do_train: false
do_eval: true
do_predict: false
evaluation_strategy: steps
prediction_loss_only: false
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
per_gpu_train_batch_size:
per_gpu_eval_batch_size:
gradient_accumulation_steps: 16
eval_accumulation_steps:
eval_delay: 0
learning_rate: 5e-05
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-08
max_grad_norm: 1.0
num_train_epochs: 1
max_steps: -1
lr_scheduler_type: linear
lr_scheduler_kwargs: {}
warmup_ratio: 0.0
warmup_steps: 500
log_level: passive
log_level_replica: warning
log_on_each_node: true
logging_dir: artifacts/model_trainer\runs\Mar08_13-15-12_VyomTiwari
logging_strategy: steps
logging_first_step: false
logging_steps: 10
logging_nan_inf_filter: true
save_strategy: steps
save_steps: 1000000
save_total_limit:
save_safetensors: true
save_on_each_node: false
save_only_model: false
no_cuda: false
use_cpu: false
use_mps_device: false
seed: 42
data_seed:
jit_mode_eval: false
use_ipex: false
bf16: false
fp16: false
fp16_opt_level: O1
half_precision_backend: auto
bf16_full_eval: false
fp16_full_eval: false
tf32:
local_rank: 0
ddp_backend:
tpu_num_cores:
tpu_metrics_debug: false
debug: []
dataloader_drop_last: false
eval_steps: 500
dataloader_num_workers: 0
past_index: -1
run_name: artifacts/model_trainer
disable_tqdm: false
remove_unused_columns: true
label_names:
load_best_model_at_end: false
metric_for_best_model:
greater_is_better:
ignore_data_skip: false
fsdp: []
fsdp_min_num_params: 0
fsdp_config:
  min_num_params: 0
  xla: false
  xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
deepspeed:
label_smoothing_factor: 0.0
optim: adamw_torch
optim_args:
adafactor: false
group_by_length: false
length_column_name: length
report_to:
- dvclive
ddp_find_unused_parameters:
ddp_bucket_cap_mb:
ddp_broadcast_buffers:
dataloader_pin_memory: true
dataloader_persistent_workers: false
skip_memory_metrics: true
use_legacy_prediction_loop: false
push_to_hub: false
resume_from_checkpoint:
hub_model_id:
hub_strategy: every_save
hub_token: <HUB_TOKEN>
hub_private_repo: false
hub_always_push: false
gradient_checkpointing: false
gradient_checkpointing_kwargs:
include_inputs_for_metrics: false
fp16_backend: auto
push_to_hub_model_id:
push_to_hub_organization:
push_to_hub_token: <PUSH_TO_HUB_TOKEN>
mp_parameters: ''
auto_find_batch_size: false
full_determinism: false
torchdynamo:
ray_scope: last
ddp_timeout: 1800
torch_compile: false
torch_compile_backend:
torch_compile_mode:
dispatch_batches:
split_batches: false
include_tokens_per_second: false
include_num_input_tokens_seen: false
neftune_noise_alpha:
